# Generated by Django 3.2.6 on 2024-04-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240427_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
