# Generated by Django 3.2.6 on 2024-04-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240428_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario',
        ),
    ]
