# Generated by Django 3.2.6 on 2024-04-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_estudiante_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='constrasena',
            new_name='contrasena',
        ),
    ]
